variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

  stages:
     build
     test

  build:
    stage: build
    script:
       ./gradlew assemble

  test:
    stage: build
    script:
       ./gradlew test